In [2]:
import pandas as pd

# Woking with JSON

In [3]:
url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day16%20-%20working-with-json-and-sql/train.json"

df = pd.read_json(url)

In [16]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,api_url,api_docs,api_terms,base,date,time_last_updated,rates
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,0.050110
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,1.051777
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,1.426475
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,7.270000
ANG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,0.024424
...,...,...,...,...,...,...,...
XOF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,7.637893
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,1.389489
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,3.411028
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,0.204121
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,0.301281

# Working with SQL

In [4]:
!pip install mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     - ------------------------------------- 0.5/11.9 MB 307.0 kB/s eta 0:00:37
     - ------------------------------------- 0.5/11.9 MB 307.0 kB/s eta 0:00:37
     - ------------------------------------- 0.5/11.9 MB 307.0 kB/s eta 0:00:37
     - ------------------------------------- 0.5/11.9 MB 307.0 kB/s eta 0:00:37
     - ------------------------------------- 0.5/11.9 MB 307.0 kB/s eta 0:00:37
     -- ------------------------------------ 0.8/11.9 MB 278.6 kB/s eta 0:00:40
     -- ------------------------------------ 0.8/11.9 MB 278.6 kB/s eta 0:00:40
     -- ------------------------------------ 0.8/11.9 MB 278.6 kB/s eta 0:00:40
     -- ------------------------------------ 0.8/11.9 MB 278.6 kB/s eta 0:00:40
     -- ------------------------------------ 0.8/11.9 MB 278.6 kB/s eta 0:00:40
     --- ----------------------------------- 1.0/11.9 MB 270.5 kB/s eta 0:00:40
     --- ----------------------------------- 1.0/11.9 MB 270.5 kB/s eta 0:00:40
     --- ----------------------------------- 1.0/11.9 MB 270.5 kB/s eta 0:00:40
     ---- ---------------------------------- 1.3/11.9 MB 308.2 kB/s eta 0:00:35
     ---- ---------------------------------- 1.3/11.9 MB 308.2 kB/s eta 0:00:35
     ---- ---------------------------------- 1.3/11.9 MB 308.2 kB/s eta 0:00:35
     ----- --------------------------------- 1.6/11.9 MB 324.7 kB/s eta 0:00:32
     ------ -------------------------------- 1.8/11.9 MB 366.2 kB/s eta 0:00:28
     ------ -------------------------------- 1.8/11.9 MB 366.2 kB/s eta 0:00:28
     ------ -------------------------------- 2.1/11.9 MB 379.2 kB/s eta 0:00:26
     ------- ------------------------------- 2.4/11.9 MB 418.8 kB/s eta 0:00:23
     ------- ------------------------------- 2.4/11.9 MB 418.8 kB/s eta 0:00:23
     ------- ------------------------------- 2.4/11.9 MB 418.8 kB/s eta 0:00:23
     -------- ------------------------------ 2.6/11.9 MB 426.4 kB/s eta 0:00:22
     -------- ------------------------------ 2.6/11.9 MB 426.4 kB/s eta 0:00:22
     --------- ----------------------------- 2.9/11.9 MB 437.6 kB/s eta 0:00:21
     ---------- ---------------------------- 3.1/11.9 MB 458.4 kB/s eta 0:00:19
     ---------- ---------------------------- 3.1/11.9 MB 458.4 kB/s eta 0:00:19
     ----------- --------------------------- 3.4/11.9 MB 474.9 kB/s eta 0:00:18
     ------------- ------------------------- 4.2/11.9 MB 562.0 kB/s eta 0:00:14
     -------------- ------------------------ 4.5/11.9 MB 590.9 kB/s eta 0:00:13
     -------------- ------------------------ 4.5/11.9 MB 590.9 kB/s eta 0:00:13
     --------------- ----------------------- 4.7/11.9 MB 594.5 kB/s eta 0:00:13
     --------------- ----------------------- 4.7/11.9 MB 594.5 kB/s eta 0:00:13
     ---------------- ---------------------- 5.0/11.9 MB 597.1 kB/s eta 0:00:12
     ----------------- --------------------- 5.2/11.9 MB 611.6 kB/s eta 0:00:11
     ------------------ -------------------- 5.5/11.9 MB 621.2 kB/s eta 0:00:11
     ------------------ -------------------- 5.5/11.9 MB 621.2 kB/s eta 0:00:11
     ------------------ -------------------- 5.8/11.9 MB 628.0 kB/s eta 0:00:10
     ------------------- ------------------- 6.0/11.9 MB 644.3 kB/s eta 0:00:10
     -------------------- ------------------ 6.3/11.9 MB 660.4 kB/s eta 0:00:09
     -------------------- ------------------ 6.3/11.9 MB 660.4 kB/s eta 0:00:09
     -------------------- ------------------ 6.3/11.9 MB 660.4 kB/s eta 0:00:09
     --------------------- ----------------- 6.6/11.9 MB 641.7 kB/s eta 0:00:09
     ---------------------- ---------------- 6.8/11.9 MB 655.9 kB/s eta 0:00:08
     ----------------------- --------------- 7.1/11.9 MB 667.2 kB/s eta 0:00:08
     ------------------------- ------------- 7.6/11.9 MB 700.5 kB/s eta 0:00:07
     ------------------------- ------------- 7.6/11.9 MB 700.5 kB/s eta 0:00:07
     -------------------------- ------------ 8.1/11.9 MB 721.3 kB/s eta 0:00:06
     ---------------------------- ---------- 8.7/11.9 MB 757.0 kB/s eta 0:00:05
     ----------------------------- --------- 8.9/11.9 MB 768.2 kB/s eta 0:00:04
     ------------------------------ -------- 9.2/11.9 MB 771.0 kB/s eta 0:00:04
     ------------------------------ -------- 9.2/11.9 MB 771.0 kB/s eta 0:00:04
     ------------------------------- ------- 9.4/11.9 MB 770.1 kB/s eta 0:00:04
     ------------------------------- ------- 9.4/11.9 MB 770.1 kB/s eta 0:00:04
     ------------------------------- ------- 9.4/11.9 MB 770.1 kB/s eta 0:00:04
     ------------------------------- ------- 9.7/11.9 MB 752.9 kB/s eta 0:00:03
     ------------------------------- ------ 10.0/11.9 MB 761.9 kB/s eta 0:00:03
     --------------------------------- ---- 10.5/11.9 MB 787.9 kB/s eta 0:00:02
     --------------------------------- ---- 10.5/11.9 MB 787.9 kB/s eta 0:00:02
     ---------------------------------- --- 10.7/11.9 MB 782.6 kB/s eta 0:00:02
     ------------------------------------ - 11.5/11.9 MB 824.3 kB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 835.9 kB/s  0:00:15
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp314-cp314-win_amd64.whl size=248717 sha256=f15705189ad44e670e5aad7231cc8d8acc9523906ea9f4b0c615c7bdc1f5989f
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\a2\5a\60\e03682d488f501428666827b000cfa0da00163afcd74ce2c14
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import mysql.connector

In [6]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

In [ ]:
df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

In [28]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]